### ISSUE TITLE
The docker & orb-tools orbs are included but do not seem to be used.

### ISSUE THREAD

**Issue by genevieve** [buildpacks/pack-orb#25]
If they are not being used, can they be removed or do they provide some benefit on import even if none of their commands/jobs are called?

**Comment by jromero** [comment]
@jkutner / @elbandito do any of you have some context here? I can investigate this further but it would be nice to know if there's an immediate answer to this before I do so.

**Comment by jkutner** [comment]
I'm not certain. It's possible they aren't needed

**Comment by elbandito** [comment]
I can't say for certain.  They may not be need.  Perhaps we can try removing them and see what happens?

**Comment by genevieve** [comment]
I can submit a PR but do you have any automated testing in place for the orb?

**Comment by jromero** [comment]
> I can submit a PR but do you have any automated testing in place for the orb?

Working on that as we speak. I'll try to have it up in an hour or two.

**Comment by jromero** [comment]
**Update:** 

I had hopes of being able to do most of the testing locally. Unfortunately it looks like our current implementation has a hard dependency on a machine executer which [isn't possible](https://circleci.com/docs/2.0/local-cli/#limitations-of-running-jobs-locally). 

> You cannot use the machine executor in local jobs. This is because the machine executor requires an extra VM to run its jobs.

I spent too much time trying to hack around it. :)

The reason for the current requirement appears to be on trying to cache the docker volumes created. Once we have a way to [configure cache volumes via pack](https://github.com/buildpacks/pack/issues/1077), we should be able to remove that dependency.

I've pushed a [quick draft](https://github.com/buildpacks/pack-orb/pull/26) on getting integration tests to run on circleci. It's still not functional but **on the plus side, I'm fairly confident that we can remove the orb dependencies**.
