### ISSUE TITLE
Issues in the documentation 

### ISSUE THREAD

**Issue by MattPumphreyWorkRise** [buildpacks/pack-orb#43]
So while trying out this orb, there seems to be some missing jobs and or other information.  So I am trying to use build job but this does not actual exist in the source code, so that would be helpful.

One issue that I am having is I am trying to pass parameters in from the CircleCI default values, I keep getting the variable instead of the string that comes from the circleci variables:

in my orb, up a parameter that defaults to the CIRCLE_PROJECT_REPONAME and when I pass that into the image-name fields I get an error about unable to parse, and it displays the variable name and not the variable value, as such it makes that hard to adopt into my orb and wrap it with our defaults.

**Comment by MattPumphreyWorkRise** [comment]
I have seen the example,  also I am curious as to how you got the "job" to show up even though there is not a folder for it under the src directory, which does not allow for that to be called.   So according to the documentation generated by your orb you should have a job, but the actual job does not exist in your source, or if it does I have not been able to find it. ¯\_(ツ)_/¯

**Comment by jromero** [comment]
The source for the `job` is [here](https://github.com/buildpacks/pack-orb/blob/2246e4a45311bb35d43e0eccbe17be37ebae1ed8/src/%40orb.yml#L9). 

We don't use all parts of an [_unpacked_ orb](https://circleci.com/docs/2.0/using-orbs/#orb-packing). We use only `examples` and `commands` of the unpacked strcuture.

**Comment by MattPumphreyWorkRise** [comment]
I appreciate it, that might explain while trying to use the job that is defined, there didnt actually work to be used outside of that.  Which is why only the commands are able to be used, kind of makes adoption a bit rough, just saying is all.  Also explains some the of the other behaviors that I am seeing as we go down the path of making a custom job based off of those commands but not actually using those commands.  Thanks.

**Comment by jromero** [comment]
Honestly, I'm not sure I understand. In what context are you trying to use the job since it should be usable as per the examples. Could you provide a config or other context?

**Comment by kcirtapfromspace** [comment]
copying the examples directly into a workflow only returns strings of errors. 

```
Error calling workflow: 'build_test_and_deploy'
Cannot find orb 'buildpacks' looking for job named 'buildpacks/build'

cloudfoundry_circleci
130
Error calling workflow: 'build_test_and_deploy'
Cannot find a definition for job named build

cloudfoundry_circleci
129
Error calling workflow: 'build_test_and_deploy'
Error calling job: 'build'
Cannot find orb 'buildpacks' looking for command named 'buildpacks/build'

cloudfoundry_circleci
128
Error calling workflow: 'build_test_and_deploy'
Cannot find orb 'buildpacks' looking for job named 'buildpacks/build'

cloudfoundry_circleci
127
Error calling workflow: 'build_test_and_deploy'
Cannot find orb 'buildpacks' looking for job named 'buildpacks/build'

cloudfoundry_circleci
126
Error calling workflow: 'build_test_and_deploy'
Cannot find orb 'buildpacks' looking for job named 'buildpacks/build'

cloudfoundry_circleci
125
Error calling workflow: 'build_test_and_deploy'
Cannot find orb 'buildpacks' looking for job named 'buildpacks/build'

cloudfoundry_circleci
124
Error calling workflow: 'build_test_and_deploy'
Error calling job: 'paketo_build'
Cannot find orb 'buildpacks' looking for command named 'buildpacks/build'

cloudfoundry_circleci
123
Error calling workflow: 'build_test_and_deploy'
Error calling job: 'paketo_build'
Cannot find orb 'buildpacks' looking for command named 'buildpacks/build'
```

**Comment by kcirtapfromspace** [comment]
version: 2.1

orbs:
  pack: buildpacks/pack@0.2.4
  
executors:
  base-executor:
    docker:
      - image: cimg/base:2023.05
jobs:
  publish:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            docker load -i /tmp/workspace/images/myimage.tgz
            docker push myimage

workflows:
  main:
      jobs:
        - buildpacks/build:
            builder: heroku/buildpacks:18
            image-file: myimage.tgz
            image-name: myimage
        - publish:
            requires:
              - buildpacks/build
              
              
Error calling workflow: 'main'
Cannot find orb 'buildpacks' looking for job named 'buildpacks/build'
